
DROP DATABASE IF EXISTS TASTY_SEARCH;
CREATE DATABASE IF NOT EXISTS TASTY_SEARCH DEFAULT  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP USER IF EXISTS 'tasty'@'localhost';
CREATE USER 'tasty'@'localhost' IDENTIFIED BY 'nottellingu' PASSWORD EXPIRE NEVER;
GRANT CREATE, EXECUTE,SELECT,INSERT,UPDATE,DELETE ON TASTY_SEARCH.* TO 'tasty'@'localhost' ;

FLUSH PRIVILEGES;

DROP USER IF EXISTS 'tasty_migrate'@'localhost';
CREATE USER 'tasty_migrate'@'localhost' IDENTIFIED BY 'migratepassword' PASSWORD EXPIRE NEVER;
GRANT CREATE, ALTER,DROP,INDEX,EXECUTE,SELECT,INSERT,UPDATE,DELETE ON TASTY_SEARCH.* TO 'tasty_migrate'@'localhost' ;

FLUSH PRIVILEGES ;